import { IForms } from "@/src/shared/types/types";

const inputsArray: IForms[] = [
  {
    name: "lastName",
    title: "Your last name",
    placeholder: "For Example Doe",
    required: true,
    type: "input",
    errorAlert: "Incorrect last name",
    requiredAlert: "Enter your last name",
  },
  {
    name: "firstName",
    title: "Your first name",
    placeholder: "For Example Jhon",
    required: true,
    type: "input",

    errorAlert: "Incorrect first name",
    requiredAlert: "Enter your rirst name",
  },
  {
    name: "patronymic",
    title: "Your patronymic",
    placeholder: "For Example Victorovich",
    required: false,
    type: "input",
    requiredAlert: "Enter your first name",
    errorAlert: "Incorrect patronymic",
  },
  {
    name: "term",
    title: "Select term",
    placeholder: "6 month",
    required: true,
    type: "selector",
    selectorArray: [1, 2, 3, 4, 5, 6],
    errorAlert: "Incorrect term",
    requiredAlert: "Enter term",
  },
  {
    name: "email",
    title: "Your email",
    placeholder: "test@gmail.com",
    required: true,
    type: "input",

    errorAlert: "Incorrect email address",
    requiredAlert: "Enter your email address",
  },
  {
    name: "birth",
    title: "Your date of birth",
    placeholder: "Select Date and Time",
    required: true,
    type: "calendar",
    errorAlert: "You must be 18 and older",
    requiredAlert: "Enter your date of birth",
  },
  {
    name: "passportSeries",
    title: "Your passport series",
    placeholder: "0000",
    required: true,
    type: "input",
    mask: "0000",
    errorAlert: "The series must be 4 digits",
    requiredAlert: "Enter your passport series",
  },
  {
    name: "passportNumber",
    title: "Your passport number",
    placeholder: "000000",
    required: true,
    type: "input",
    mask: "000000",
    errorAlert: "The series must be 6 digits",
    requiredAlert: "Enter your passport number",
  },
];
export default inputsArray;
