import { IForms } from "@/src/shared/types/types";

export const inputsArray: IForms[] = [
  {
    name: "gender",
    title: "What's your gender",
    placeholder: "",
    required: true,
    type: "selector",
    selectorArray: ["", "Male", "Female"],
    errorAlert: "Incorrect gender",
    requiredAlert: "Select one of the options",
  },
  {
    name: "maritalStatus",
    title: "Your marital status",
    placeholder: "For Example Doe",
    required: true,
    type: "selector",
    selectorArray: ["", "Married", "Divorced", "Single", "Widow/Widower"],
    errorAlert: "Incorrect marital status",
    requiredAlert: "Enter your marital status",
  },
  {
    name: "dependentAmount",
    title: "Your number of dependents",
    placeholder: "3",
    required: true,
    type: "input",
    errorAlert: "Incorrect number of dependents",
    requiredAlert: "Enter your number of dependents",
  },
  {
    name: "passportIssueDate",
    title: "Date of issue of the passport",
    placeholder: "Select Date and Time",
    required: true,
    type: "calendar",
    errorAlert: "Incorrect date of passport issue date",
    requiredAlert: "Enter your date of issue of the passport",
  },
  {
    name: "passportIssueBranch",
    title: "Division code",
    placeholder: "000000",
    required: true,
    type: "input",
    errorAlert: "Incorrect date of passport issue date",
    requiredAlert: "Enter your date of issue of the passport",
  },
];

export const employerInputsArray: IForms[] = [
  {
    name: "employmentStatus",
    title: "Your marital status",
    placeholder: "For Example Doe",
    required: true,
    type: "selector",
    selectorArray: [
      "",
      "Unemployed",
      "Self employed",
      "Employed",
      "Buisness owner",
    ],
    errorAlert: "Incorrect employment status",
    requiredAlert: "Select one of the options",
  },
  {
    name: "employerINN",
    title: "Your employer INN",
    placeholder: "000000000000",
    required: true,
    type: "input",
    errorAlert: "Department code must be 12 digits",
    requiredAlert: "Enter your INN",
  },
  {
    name: "salary",
    title: "Your salary",
    placeholder: "For example 100 000",
    required: true,
    type: "input",
    errorAlert: "Enter your salary",
    requiredAlert: "Enter your salary",
  },
  {
    name: "position",
    title: "Your position",
    placeholder: "",
    required: true,
    type: "selector",
    selectorArray: ["", "Worker", "Mid manager", "Top manager", "Owner"],
    errorAlert: "Incorrect position",
    requiredAlert: "Select one of the options",
  },
  {
    name: "workExperienceTotal",
    title: "Your work experience total",
    placeholder: "For example 10",
    required: true,
    type: "input",
    errorAlert: "Enter your work experience total",
    requiredAlert: "Enter your work experience total",
  },
  {
    name: "workExperienceCurrent",
    title: "Your work experience current",
    placeholder: "For example 2",
    required: true,
    type: "input",
    errorAlert: "Enter your work experience current",
    requiredAlert: "Enter your work experience current",
  },
];
